/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-09-08 10:48:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/workspace/workspace_java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/peanutbutter/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1725776852058L));
    _jspx_dependants.put("jar:file:/C:/workspace/workspace_java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/peanutbutter/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/workspace/workspace_java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/peanutbutter/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        background-color: #E9E4DC;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container {\r\n");
      out.write("        margin: 0 100px;\r\n");
      out.write("        background-color: #E9E4DC;\r\n");
      out.write("        padding: 20px 100px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    span {\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .inputText {\r\n");
      out.write("        margin-left: 20px;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        vertical-align: top;\r\n");
      out.write("        padding-left: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    textarea {\r\n");
      out.write("        width: 90%;\r\n");
      out.write("        height: 150px;\r\n");
      out.write("        padding: 0px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .commentSection {\r\n");
      out.write("        height: 180px;\r\n");
      out.write("        margin: 0px 100px;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        overflow-y: auto;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .left {\r\n");
      out.write("        width: 150px;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        padding: 5px 0px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .right {\r\n");
      out.write("        width: 650px;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        padding: 5px 0px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .tbody td:nth-child(1) {\r\n");
      out.write("        width: 16%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 5px 0px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .tbody td:nth-child(2) {\r\n");
      out.write("        width: 85%;\r\n");
      out.write("        padding-left: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .commentRegSection {\r\n");
      out.write("        height: 70px;\r\n");
      out.write("        margin: 0 100px;\r\n");
      out.write("        padding: 5px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .commentReg {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        width: 600px;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .regBtn {\r\n");
      out.write("        margin-left: 20px;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        background-color: rgb(169, 169, 169);\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        color: white;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .comment {\r\n");
      out.write("        border-left: 2px solid gray;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .buttonGroup {\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        text-align: right;\r\n");
      out.write("    }\r\n");
      out.write("    .buttonGroup a, .deleteBtn{\r\n");
      out.write("       display : inline-block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn {\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        margin-left: 10px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        color: white;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write(".editBtn {\r\n");
      out.write("    background-color: #4CAF50;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    margin-left: 10px;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    color: white;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("    text-decoration-color: #4CAF50;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".deleteBtn {\r\n");
      out.write("    background-color: #f44336;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    margin-left: 10px;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    color: white;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-container {\r\n");
      out.write("    display: inline-block; /* 또는 flex를 사용해도 됩니다 */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <form method=\"get\" action=\"detail\">\r\n");
      out.write("                <div style=\"margin-top: 10px;\">\r\n");
      out.write("                    <span>제목</span><input class=\"inputText\" type=\"text\" id=\"title\" name=\"title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDTO.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    <span style=\"margin-left: 30px;\">작성자</span><input class=\"inputText\" type=\"text\" id=\"writer\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDTO.ename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <div style=\"margin-top: 10px;\">\r\n");
      out.write("                    <span>내용</span><textarea class=\"inputText\" id=\"content\" name=\"content\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDTO.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("                <div class=\"buttonGroup\">\r\n");
      out.write("                    <a href=\"modify?bno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDTO.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"editBtn\">수정</a>\r\n");
      out.write("                    <form method=\"post\" action=\"delete\" style=\"display:inline-block\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"bno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDTO.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  style=\"display: inline-block; margin: 0;\">\r\n");
      out.write("                    <input type=\"submit\" value=\"삭제\" class=\"deleteBtn\" style=\"border: none; cursor: pointer;\">\r\n");
      out.write("                </form>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div class=\"commentSection\">\r\n");
      out.write("        <table class=\"table\">\r\n");
      out.write("            <tbody class=\"tbody\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!--                 <tr> -->\r\n");
      out.write("<!--                     <td>작성자1</td> -->\r\n");
      out.write("<!--                     <td class=\"comment\">내용1</td> -->\r\n");
      out.write("<!--                 </tr> -->\r\n");
      out.write("<!--                 <tr> -->\r\n");
      out.write("<!--                     <td>작성자2</td> -->\r\n");
      out.write("<!--                     <td class=\"comment\">내용2</td> -->\r\n");
      out.write("<!--                 </tr> -->\r\n");
      out.write("<!--                 <tr> -->\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!--                 </tr> -->\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"commentRegSection\">\r\n");
      out.write("        <form id=\"commentForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/comment\" method=\"post\">\r\n");
      out.write("           <div style=\"display: inline-block;\">\r\n");
      out.write("           <input type = \"hidden\" name=\"bno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardDTO.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("           <input type = \"hidden\" name=\"ename\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO.ename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("               <textarea class=\"commentReg\" placeholder=\"댓글 입력 ...\" name=\"reply\"></textarea>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div style=\"display: inline-block;\">\r\n");
      out.write("               <input type=\"submit\" value=\"작성\" class=\"regBtn\">\r\n");
      out.write("           </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("//     function commitReg() {\r\n");
      out.write("//         let comment = document.querySelector('.commentReg').value;\r\n");
      out.write("\r\n");
      out.write("//         let postIndex = sessionStorage.getItem('postIndex');\r\n");
      out.write("//         let posts = JSON.parse(sessionStorage.getItem('posts')) || [];\r\n");
      out.write("\r\n");
      out.write("//         let post = posts.find(p => p.index == postIndex);\r\n");
      out.write("\r\n");
      out.write("//         if (post) {\r\n");
      out.write("//             if (!post.comments) {\r\n");
      out.write("//                 post.comments = []; //아무댓글도 없었을 때 처음 배열 만들기\r\n");
      out.write("//             }\r\n");
      out.write("\r\n");
      out.write("//             post.comments.push(comment);\r\n");
      out.write("\r\n");
      out.write("//             // 세션 스토리지에 저장\r\n");
      out.write("//             sessionStorage.setItem('posts', JSON.stringify(posts));\r\n");
      out.write("\r\n");
      out.write("//             // 댓글을 화면에 추가\r\n");
      out.write("//             let tbody = document.querySelector('.tbody');\r\n");
      out.write("//             let newRow = document.createElement('tr');\r\n");
      out.write("//             newRow.innerHTML = \r\n");
      out.write("//                 `\r\n");
      out.write("//                 <td>작성자</td>\r\n");
      out.write("//                 <td class=\"comment\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("//                 `;\r\n");
      out.write("//             tbody.appendChild(newRow);\r\n");
      out.write("\r\n");
      out.write("//             // 댓글 입력 필드 초기화\r\n");
      out.write("//             document.querySelector('.commentReg').value = '';\r\n");
      out.write("//         } else {\r\n");
      out.write("//             alert('게시글을 찾을 수 없습니다.');\r\n");
      out.write("//         }\r\n");
      out.write("//     }\r\n");
      out.write("\r\n");
      out.write("    function editPost() {\r\n");
      out.write("        alert('게시글을 수정합니다.');\r\n");
      out.write("        // 수정 로직을 여기에 추가\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function deletePost() {\r\n");
      out.write("        if (confirm('정말 삭제하시겠습니까?')) {\r\n");
      out.write("            alert('게시글이 삭제되었습니다.');\r\n");
      out.write("            // 삭제 로직을 여기에 추가\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/board/boardDetail.jsp(184,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("commentDTO");
      // /WEB-INF/board/boardDetail.jsp(184,12) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${commentList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("               <tr>\r\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${commentDTO.ename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                    <td class=\"comment\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${commentDTO.reply}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                </tr>\r\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
