/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-09-09 01:46:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BaljuDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    * {\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container {\r\n");
      out.write("        background-color: #F0F0E8;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .top {\r\n");
      out.write("        color: #676767;\r\n");
      out.write("        font-size: 24px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        height: 15vh;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .title {\r\n");
      out.write("        padding-top: 30px;\r\n");
      out.write("        margin-left: 100px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .title img {\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .title span {\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .section {\r\n");
      out.write("        margin: 0 100px;\r\n");
      out.write("        height: 70vh;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .tableTopDiv {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 30%;\r\n");
      out.write("        padding-top: 3px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table {\r\n");
      out.write("        border-collapse: collapse;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    th {\r\n");
      out.write("        background-color: #b6b6b6;\r\n");
      out.write("        border-right: 1px solid white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    td {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .tbody tr {\r\n");
      out.write("        border-bottom: 1px solid lightgray;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    tr th,\r\n");
      out.write("    tr td {\r\n");
      out.write("        padding: 5px 0px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .thead th:nth-child(1) {\r\n");
      out.write("        width: 5%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .thead th:nth-child(2) {\r\n");
      out.write("        width: 15%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .thead th:nth-child(3) {\r\n");
      out.write("        width: 15%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .thead th:nth-child(4) {\r\n");
      out.write("        width: 15%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .thead th:nth-child(5) {\r\n");
      out.write("        width: 10%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .thead th:nth-child(6) {\r\n");
      out.write("        width: 10%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .thead th:nth-child(7) {\r\n");
      out.write("        width: 10%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .thead th:nth-child(8) {\r\n");
      out.write("        width: 10%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .Btn_css {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        padding: 5px;\r\n");
      out.write("        background-color: #3F3B3B;\r\n");
      out.write("        color: white;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .regBtn {\r\n");
      out.write("        margin: 0 100px;\r\n");
      out.write("        text-align: right;\r\n");
      out.write("        margin-top: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .inputText {\r\n");
      out.write("        height: 25px;\r\n");
      out.write("        margin-left: 30px;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .span {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        width: 100px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        vertical-align: top;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        line-height: 30px;\r\n");
      out.write("        margin-left: 100px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .margin {\r\n");
      out.write("        margin-left: 100px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .temp {\r\n");
      out.write("        height: 30px;\r\n");
      out.write("        margin: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"text\"] {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"top\">\r\n");
      out.write("            <div class=\"title\">\r\n");
      out.write("                <img src=\"image/BOM.png\" style=\"width: 30px;\">\r\n");
      out.write("                <span>PO202407310001</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"section\">\r\n");
      out.write("            <div class=\"tableTopDiv\">\r\n");
      out.write("                <div class=\"temp\">\r\n");
      out.write("                    <span class=\"span\">P/O NO(*)</span> <input type=\"text\" class=\"inputText\" id=\"PO_No\" value=\"PO202407310001\">\r\n");
      out.write("                    <span class=\"span margin\">P/O 일자(*)</span> <input type=\"text\" class=\"inputText\" id=\"PO_date\" value=\"2024-08-05\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"temp\">\r\n");
      out.write("                    <span class=\"span\">거래처(*)</span> <input type=\"text\" class=\"inputText\" id=\"account\" value=\"순양물산\">\r\n");
      out.write("                    <span class=\"span margin\">통화(*)</span> <input type=\"text\" class=\"inputText\" id=\"KRW\" value=\"KRW\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"temp\">\r\n");
      out.write("                    <span class=\"span\">비고사항</span> <input style=\"width: 350px;\" type=\"text\" class=\"inputText\" id=\"remark\">\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <table class=\"table\">\r\n");
      out.write("                <thead class=\"thead\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th> </th>\r\n");
      out.write("                        <th>부품명</th>\r\n");
      out.write("                        <th>모델명</th>\r\n");
      out.write("                        <th>부품코드</th>\r\n");
      out.write("                        <th>납품예정일</th>\r\n");
      out.write("                        <th>단가</th>\r\n");
      out.write("                        <th>발주 수량</th>\r\n");
      out.write("                        <th>합계</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody class=\"tbody\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td>CPU</td>\r\n");
      out.write("                        <td>Intel Core i9-9900K</td>\r\n");
      out.write("                        <td>A01-01</td>\r\n");
      out.write("                        <td>2024-08-01</td>\r\n");
      out.write("                        <td>500,000</td>\r\n");
      out.write("                        <td>10</td>\r\n");
      out.write("                        <td>5,000,000</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td>RAM</td>\r\n");
      out.write("                        <td>DDR4-3200</td>\r\n");
      out.write("                        <td>A02-01</td>\r\n");
      out.write("                        <td>2024-08-01</td>\r\n");
      out.write("                        <td>200,000</td>\r\n");
      out.write("                        <td>10</td>\r\n");
      out.write("                        <td>2,000,000</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td>메인보드</td>\r\n");
      out.write("                        <td>ASUS ROG</td>\r\n");
      out.write("                        <td>A03-01</td>\r\n");
      out.write("                        <td>2024-08-01</td>\r\n");
      out.write("                        <td>300,000</td>\r\n");
      out.write("                        <td>10</td>\r\n");
      out.write("                        <td>3,000,000</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("         \r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"regBtn\">\r\n");
      out.write("            <span class=\"Btn_css\" style=\"padding:10px\" onclick=\"commitReg()\">완료</span>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function commitReg(){\r\n");
      out.write("        window.location.href=\"In\";\r\n");
      out.write("    }\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
