/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-09-09 01:26:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class PLinsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/workspace/workspace_java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/peanutbutter/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1725776852058L));
    _jspx_dependants.put("jar:file:/C:/workspace/workspace_java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/peanutbutter/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/workspace/workspace_java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/peanutbutter/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    * {\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container {\r\n");
      out.write("        background-color: #F0F0E8;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .top {\r\n");
      out.write("        color: #676767;\r\n");
      out.write("        font-size: 24px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        height: 12vh;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .title {\r\n");
      out.write("        padding-top: 30px;\r\n");
      out.write("        margin-left: 100px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .title img {\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("        /* 이미지와 텍스트의 높낮이를 맞추기 위해 추가 */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .title span {\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("        /* 이미지와 텍스트의 높낮이를 맞추기 위해 추가 */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .search_container {\r\n");
      out.write("        margin: 0 20px;\r\n");
      out.write("        height: 81vh;\r\n");
      out.write("        background-color: #E9E4DC;\r\n");
      out.write("        overflow: auto;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn:active {\r\n");
      out.write("        transform: scale(0.95);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn2:active {\r\n");
      out.write("        transform: scale(0.95);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn {\r\n");
      out.write("        background-color: #A2A2A2;\r\n");
      out.write("        color: #FFFFFF;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn2 {\r\n");
      out.write("        margin: 10px 10px 0 0;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        background-color: #A2A2A2;\r\n");
      out.write("        color: #FFFFFF;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .searchcon {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: left;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        margin: 20px 0 0 40px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .search-box {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        margin-right: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .search-box1 {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        width: 280px;\r\n");
      out.write("        margin-right: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .search-box1 input[type=\"text\"] {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        padding-right: 40px;\r\n");
      out.write("        /* Make space for the button */\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .search-box input[type=\"text\"] {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        padding-right: 40px;\r\n");
      out.write("        /* Make space for the button */\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .search-box1 button {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        right: 0;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        width: 95px;\r\n");
      out.write("        background-color: #D3CEC9;\r\n");
      out.write("        color: black;\r\n");
      out.write("        border: none;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .search-box1 button:active {\r\n");
      out.write("        transform: scale(0.95);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .제품select {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        margin-right: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #reg {\r\n");
      out.write("        margin-right: 50px;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        background-color: #3F3B3B;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .caution {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        display: none;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .cautionDiv {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        width: 100px;\r\n");
      out.write("        height: 100px;\r\n");
      out.write("        top: 100px;\r\n");
      out.write("        right: 100px;\r\n");
      out.write("        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.5);\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    /* 모달 스타일 */\r\n");
      out.write("    .modal {\r\n");
      out.write("        display: none;\r\n");
      out.write("        /* 기본적으로 숨김 */\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        z-index: 1;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        overflow: auto;\r\n");
      out.write("        background-color: rgba(0, 0, 0, 0.4);\r\n");
      out.write("        /* 반투명 배경 */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .modal-content {\r\n");
      out.write("        background-color: #fefefe;\r\n");
      out.write("        margin: 5% auto;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border: 1px solid #888;\r\n");
      out.write("        width: 90%;\r\n");
      out.write("        /* max-width: 500px; */\r\n");
      out.write("    }\r\n");
      out.write("    .modal-content iframe {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            height: 90%;\r\n");
      out.write("            border: none;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"top\">\r\n");
      out.write("            <div class=\"title\">\r\n");
      out.write("                <img src=\"image/BOM.png\" style=\"width: 30px;\">\r\n");
      out.write("                <span>생산계획 등록</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"search_container\">\r\n");
      out.write("			<form method=\"post\" action=\"insert_pl\">\r\n");
      out.write("            <div class=\"searchcon\">\r\n");
      out.write("                <div style=\"padding-right:15px;\">제품명(*)</div>\r\n");
      out.write("                <select style=\"height: 40px;\" class=\"제품select\" name=\"pm_name\" onchange=\"take(this)\">\r\n");
      out.write("                    <option value=\"-----\">-----</option>\r\n");
      out.write("                	");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("                <div style=\"padding-right:15px;\">제품코드(*)</div>\r\n");
      out.write("                <div class=\"search-box\">\r\n");
      out.write("                    <input id=\"제품코드\" type=\"text\" name=\"pm_code\" readonly>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"searchcon\">\r\n");
      out.write("                <div style=\"padding-right:48px;\">단위</div>\r\n");
      out.write("                <div class=\"search-box\">\r\n");
      out.write("                    <input id=\"unit\" type=\"text\" name=\"pm_unit\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"searchcon\">\r\n");
      out.write("\r\n");
      out.write("                <div style=\"padding-right:17px;\">계획수량</div>\r\n");
      out.write("                <div class=\"search-box\">\r\n");
      out.write("                    <input type=\"text\" id=\"count\" oninput=\"caution(this)\" name=\"pl_amount\">\r\n");
      out.write("                </div>\r\n");
      out.write("                생산계획 기간\r\n");
      out.write("                <input style=\"height: 30px; font-size: 20px; margin-left: 11px;\" type=\"date\" id=\"date\" max=\"2025-06-20\"\r\n");
      out.write("                    min=\"2001-06-05\" value=\"2024-07-19\" name=\"date_start\" > ~\r\n");
      out.write("                <input style=\"height: 30px; font-size: 20px;\" type=\"date\" id=\"date\" max=\"2025-06-20\" min=\"2001-06-05\"\r\n");
      out.write("                    value=\"2024-09-19\" name=\"date_end\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"searchcon\">\r\n");
      out.write("                <div style=\"padding-right:17px;\">출고창고</div>\r\n");
      out.write("                <div class=\"search-box\">\r\n");
      out.write("                    <input type=\"text\" id=\"spwarehouse\" name=\"spwarehouse\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"searchcon\">\r\n");
      out.write("                <div style=\"padding-right:17px;\">비고사항</div>\r\n");
      out.write("                <input style=\"width: 705px; height: 150px;\" type=\"text\" name=\"remarks\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"text-align: end;\">\r\n");
      out.write("                <input type=\"submit\" id=\"reg\" value=\"등록\">\r\n");
      out.write("            </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <div class=\"cautionDiv\" onclick=\"showModal()\">\r\n");
      out.write("                <img src=\"image/caution.png\" class=\"caution\" alt=\"경고 이미지\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 모달 -->\r\n");
      out.write("        <div id=\"myModal\" class=\"modal\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <iframe src=></iframe>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("	\r\n");
      out.write("	function take(selectElement) {\r\n");
      out.write("    // 선택된 옵션의 값을 가져옴\r\n");
      out.write("    const selectedValue = selectElement.value;\r\n");
      out.write("    \r\n");
      out.write("    // 선택된 옵션의 data 값을 가져옴\r\n");
      out.write("    const selectedOption = selectElement.options[selectElement.selectedIndex];\r\n");
      out.write("    const selectedCode = selectedOption.getAttribute('data-code');\r\n");
      out.write("    const selectedUnit = selectedOption.getAttribute('data-unit');\r\n");
      out.write("    const selectedSpwarehouse = selectedOption.getAttribute('data-spwarehouse');\r\n");
      out.write("\r\n");
      out.write("    // 선택된 코드 값을 input vlaue로 지정\r\n");
      out.write("    const inputCode = document.getElementById('제품코드');\r\n");
      out.write("    inputCode.value = selectedCode;\r\n");
      out.write("    \r\n");
      out.write("    const inputUnit = document.getElementById('unit');\r\n");
      out.write("    inputUnit.value = selectedUnit;\r\n");
      out.write("    \r\n");
      out.write("    const inputSpwarehouse = document.getElementById('spwarehouse');\r\n");
      out.write("    inputSpwarehouse.value = selectedSpwarehouse;\r\n");
      out.write("    \r\n");
      out.write("    // 콘솔에 출력 (디버깅용)\r\n");
      out.write("    console.log('선택된 값:', selectedValue);\r\n");
      out.write("    console.log('선택된 코드:', selectedCode);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    function caution(element) {\r\n");
      out.write("        let count = document.querySelector('#count')\r\n");
      out.write("        let countNum = parseFloat(count.value);\r\n");
      out.write("        let code = document.querySelector('#제품코드').value;\r\n");
      out.write("        console.log(code)\r\n");
      out.write("        let cautionDiv = document.querySelector('.caution');\r\n");
      out.write("        let cautionDiv2 = document.querySelector('.cautionDiv');\r\n");
      out.write("\r\n");
      out.write("        if (code === \"GRAM-001\" && countNum > 99) {\r\n");
      out.write("            cautionDiv.style.display = 'block'\r\n");
      out.write("            cautionDiv2.style.display = 'block'\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function showModal() {\r\n");
      out.write("        document.querySelector(\"#myModal\").style.display = \"block\";\r\n");
      out.write("    }\r\n");
      out.write("    function closeModal() {\r\n");
      out.write("        document.querySelector(\"#myModal\").style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    window.onclick = function (event) {\r\n");
      out.write("        if (event.target == document.querySelector(\"#myModal\")) {\r\n");
      out.write("            closeModal();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/PLinsert.jsp(212,17) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("PM");
      // /WEB-INF/views/PLinsert.jsp(212,17) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                    <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PM.product_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("                    \r\n");
            out.write("                     data-code = \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PM.product_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("                     data-unit = \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PM.unit }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("                     data-spwarehouse = \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PM.shipping_warehouse}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("                     >");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PM.product_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write('(');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PM.product_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")</option>\r\n");
            out.write("                    \r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
