/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-09-09 02:45:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Production_0020performance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            background-color: #F0F0E8;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background-color: #F0F0E8\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .top {\r\n");
      out.write("            color: #676767;\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            height: 8vh;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .title {\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            margin-left: 100px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .title img {\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("            /* 이미지와 텍스트의 높낮이를 맞추기 위해 추가 */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .title span {\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("            /* 이미지와 텍스트의 높낮이를 맞추기 위해 추가 */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search_container {\r\n");
      out.write("            margin: 0 100px;\r\n");
      out.write("            height: 17vh;\r\n");
      out.write("            background-color: #E9E4DC;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: left;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            padding-left: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .span1 {\r\n");
      out.write("            display: flex;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search_item {\r\n");
      out.write("            margin: 10px 100px;\r\n");
      out.write("            height: 43vh;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            table-layout: fixed;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th,\r\n");
      out.write("        td {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tableTop {\r\n");
      out.write("            background-color: #848484;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .tableBody {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("            margin-bottom: 0px;\r\n");
      out.write("            margin-top: 0px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .title {\r\n");
      out.write("            vertical-align: bottom;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .calendar {\r\n");
      out.write("            height: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        td>input {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            width: 80px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .commit {\r\n");
      out.write("            margin: 50px 100px;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .save,\r\n");
      out.write("        .inquire {\r\n");
      out.write("            border: #676767;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            background-color: #848484;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            width: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .item {\r\n");
      out.write("            vertical-align: text-bottom;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .record {\r\n");
      out.write("            padding-top: 8px;\r\n");
      out.write("            padding-bottom: 1px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .part {\r\n");
      out.write("            padding-bottom: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        div.inquiry input {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            background-color: black;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .inquiry {\r\n");
      out.write("            margin: 0 100px;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        div.inquiry span {\r\n");
      out.write("            float: left;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tableBody tr {\r\n");
      out.write("            border-bottom: 1px solid rgb(188, 184, 184);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search_container {\r\n");
      out.write("            margin: 0 100px;\r\n");
      out.write("            height: 10vh;\r\n");
      out.write("            background-color: #E9E4DC;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .select {\r\n");
      out.write("            margin-right: 20px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .inputTextHeight {\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn2 {\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("            ;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        thead th:nth-child(1) {\r\n");
      out.write("            width: 5%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        thead th:nth-child(2) {\r\n");
      out.write("            width: 10%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        thead th:nth-child(3) {\r\n");
      out.write("            width: 10%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        thead th:nth-child(4) {\r\n");
      out.write("            width: 10%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        thead th:nth-child(5) {\r\n");
      out.write("            width: 10%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        thead th:nth-child(6) {\r\n");
      out.write("            width: 10%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        thead th:nth-child(7) {\r\n");
      out.write("            width: 7%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        thead th:nth-child(8) {\r\n");
      out.write("            width: 5%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        thead th:nth-child(9) {\r\n");
      out.write("            width: 5%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        thead th:nth-child(10) {\r\n");
      out.write("            width: 7%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        thead th:nth-child(11) {\r\n");
      out.write("            width: 5%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .select_all {\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .deselect_all {\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tableTop {\r\n");
      out.write("            position: sticky;\r\n");
      out.write("            top: 0;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script>\r\n");
      out.write("        window.onload = function () {\r\n");
      out.write("            let btn = document.querySelector(\".btn\")\r\n");
      out.write("\r\n");
      out.write("            // let chk = document.querySelectorAll(\"input[type='checkbox']\")\r\n");
      out.write("\r\n");
      out.write("            btn.addEventListener(\"click\", function () {\r\n");
      out.write("                let tbody = document.querySelector(\".tableBody\");\r\n");
      out.write("                let newRow = document.createElement(\"tr\");\r\n");
      out.write("                newRow.classList.add(\"row\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                let cells = `\r\n");
      out.write("                         <td><input type=\"checkbox\" class=\"chk\" style=\"width : 90%;\"></td>\r\n");
      out.write("                         <td><input type=\"text\" style=\"width : 90%;\"></td>\r\n");
      out.write("                         <td><input type=\"text\" style=\"width : 90%;\"></td>\r\n");
      out.write("                         <td><input type=\"text\" style=\"width : 90%;\"></td>\r\n");
      out.write("                         <td><input type=\"text\" style=\"width : 90%;\"></td>\r\n");
      out.write("                         <td><input type=\"text\" style=\"width : 90%;\"></td>\r\n");
      out.write("                         <td><input type=\"text\" style=\"width : 90%;\"></td>\r\n");
      out.write("                        <td><input type=\"text\" style=\"width : 90%;\"></td>\r\n");
      out.write("                         <td><input type=\"text\" style=\"width : 90%;\"></td>\r\n");
      out.write("                         <td><input type=\"text\" style=\"width : 90%;\"></td>\r\n");
      out.write("                         <td><input type=\"text\" style=\"width : 90%;\"></td>\r\n");
      out.write("                         `\r\n");
      out.write("                    ;\r\n");
      out.write("\r\n");
      out.write("                newRow.innerHTML = cells\r\n");
      out.write("                tbody.appendChild(newRow);\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            let select_all = document.querySelector(\".select_all\")\r\n");
      out.write("            select_all.addEventListener(\"click\", function () {\r\n");
      out.write("                //hasClass\r\n");
      out.write("                if (select_all.classList.contains(\"select_all\")) {\r\n");
      out.write("                    select_all.classList.remove(\"select_all\");\r\n");
      out.write("                    select_all.classList.add(\"deselect_all\");\r\n");
      out.write("                    select_all.value = \"전체해제\";\r\n");
      out.write("                    let chkbox = document.querySelectorAll(\".chk\")\r\n");
      out.write("                    for (let i = 0; i < chkbox.length; i++) {\r\n");
      out.write("                        chkbox[i].checked = true;\r\n");
      out.write("                        // if (chk_all.checked == false) {\r\n");
      out.write("                        //     chkbox[i].checked = false;\r\n");
      out.write("                        // } \r\n");
      out.write("                    }\r\n");
      out.write("                } else {\r\n");
      out.write("                    select_all.classList.remove(\"deselect_all\");\r\n");
      out.write("                    select_all.classList.add(\"select_all\");\r\n");
      out.write("                    select_all.value = \"전체선택\";\r\n");
      out.write("\r\n");
      out.write("                    let chkbox = document.querySelectorAll(\".chk\")\r\n");
      out.write("                    for (let i = 0; i < chkbox.length; i++) {\r\n");
      out.write("                        chkbox[i].checked = false;\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            let del = document.querySelector(\".btn2\")\r\n");
      out.write("            del.addEventListener(\"click\", function () {\r\n");
      out.write("                let chkbox = document.querySelectorAll(\".chk\");\r\n");
      out.write("                chkbox.forEach(function (chkbox) {\r\n");
      out.write("                    if (chkbox.checked) {\r\n");
      out.write("                        // 체크박스가 포함된 td의 부모 tr 요소를 선택하여 삭제\r\n");
      out.write("                        let td = chkbox.parentElement;\r\n");
      out.write("                        let row = td.parentElement;\r\n");
      out.write("                        row.remove();\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"top\">\r\n");
      out.write("            <div class=\"title\"><img src=\"image/directory.png\">생산실적</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"search_container\">\r\n");
      out.write("            <div class=\"search\">\r\n");
      out.write("                <select id=\"select\" name=\"choice\" class=\"inputTextHeight\">\r\n");
      out.write("                    <option value=\"select\">-------</option>\r\n");
      out.write("                    <option value=\"생산계획No\">생산계획NO</option>\r\n");
      out.write("                    <option value=\"제품명\">제품명</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <input id=\"searchText\" type=\"text\" placeholder=\"Search...\"\r\n");
      out.write("                    class=\"inputTextHeight\">&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                <img class=\"searchBtn\" src=\"image/search.png\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- <div class=\"inquiry\">\r\n");
      out.write("            <span> <input type=\"button\" value=\"추가\" class=\"btn\"></span><span><input type=\"button\" value=\"삭제\"\r\n");
      out.write("                    class=\"btn2\"></span>\r\n");
      out.write("            <span><input type=\"button\" value=\"전체선택\" class=\"select_all\"></span>\r\n");
      out.write("\r\n");
      out.write("            <input type=\"button\" value=\"공정별 자재투입 현황 조회\">\r\n");
      out.write("            <input type=\"button\" value=\"공정별 생산 실적 조회\">\r\n");
      out.write("        </div> -->\r\n");
      out.write("        <div class=\"search_item\">\r\n");
      out.write("            <table>\r\n");
      out.write("                <thead class=\"tableTop\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th></th>\r\n");
      out.write("                        <th style=\"font-size: 13px;\">생산계획서NO</th>\r\n");
      out.write("                        <th>제품명</th>\r\n");
      out.write("                        <th>지시일자</th>\r\n");
      out.write("                        <th>계획수량</th>\r\n");
      out.write("                        <th>생산</th>\r\n");
      out.write("                        <th>양품</th>\r\n");
      out.write("                        <th>불량품</th>\r\n");
      out.write("                        <th>잔량</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody class=\"tableBody\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><input type=\"checkbox\"></td>\r\n");
      out.write("                        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].plan_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                        <td style=\"font-size: 15px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].product_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].plan_start_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].plan_amount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                        <td>14</td>\r\n");
      out.write("                        <td>13</td>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0].plan_amount-14}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"commit\"><span class=\"save\">저장</span></div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
